DROP USER JPA25 CASCADE;

CREATE USER JPA25 IDENTIFIED BY JPA25;
GRANT CONNECT, RESOURCE TO JPA25;

CONNECT JPA25/JPA25

CREATE SEQUENCE SEQ_PAGAMENTO;

CREATE TABLE PAGAMENTO
(ID               NUMBER(5)
   CONSTRAINT PAGAMENTO_ID_PK
   PRIMARY KEY,
 VALOR            NUMBER(9,2),
 DATA_PGTO        DATE);

CREATE TABLE CONTA
(ID               NUMBER(5)
   CONSTRAINT CONTA_ID_PK
   PRIMARY KEY
   CONSTRAINT CONTA_PAGAMENTO_FK
   REFERENCES PAGAMENTO(ID),
 BANCO            VARCHAR2(10),
 AGENCIA          VARCHAR2(10),
 CONTA            VARCHAR2(10));

CREATE TABLE CARTAO
(ID               NUMBER(5)
   CONSTRAINT CARTAO_ID_PK
   PRIMARY KEY
   CONSTRAINT CARTAO_PAGAMENTO_FK
   REFERENCES PAGAMENTO(ID),
 NUMERO           VARCHAR2(10),
 MES_EXP          CHAR(02),
 ANO_EXP          CHAR(04));

