DROP USER JPA27 CASCADE;
CREATE USER JPA27 IDENTIFIED BY JPA27;
GRANT CONNECT, RESOURCE TO JPA27;

CONNECT JPA27/JPA27

CREATE SEQUENCE SEQ_PRODUTO;

CREATE TABLE PRODUTO
(ID             NUMBER(5)
   CONSTRAINT PRODUTO_ID_PK
   PRIMARY KEY,
 NOME           VARCHAR2(30) 
   CONSTRAINT PRODUTO_NOME_NN
   NOT NULL,
 DESCRICAO      VARCHAR2(40),
 LANCE_MINIMO  NUMBER(8,2)
   CONSTRAINT PRODUTO_LANCE_MINIMO_NN
   NOT NULL,
 DATA_CADASTRO  DATE
   CONSTRAINT PRODUTO_DATA_CADASTRO_NN
   NOT NULL,
 DATA_VENDA     DATE);

CREATE TABLE LANCE
(ID_PRODUTO     NUMBER(5)
   CONSTRAINT LANCE_PRODUTO_FK
   REFERENCES PRODUTO(ID),
 NUMERO_LANCE   NUMBER(5),
 VALOR          NUMBER(8,2)
   CONSTRAINT LANCE_VALOR_NN
   NOT NULL,
 DATA_CRIACAO   DATE
   CONSTRAINT LANCE_DATA_CRIACAO_NN
   NOT NULL,
CONSTRAINT LANCE_PK
PRIMARY KEY(ID_PRODUTO, NUMERO_LANCE));
