DROP USER EJB01 CASCADE;
DROP USER EJB02 CASCADE;
DROP USER EJB03 CASCADE;

CREATE USER EJB01 IDENTIFIED BY EJB01;
CREATE USER EJB02 IDENTIFIED BY EJB02;
CREATE USER EJB03 IDENTIFIED BY EJB03;

GRANT CONNECT, RESOURCE TO EJB01;
GRANT CONNECT, RESOURCE TO EJB02;
GRANT CONNECT, RESOURCE TO EJB03;


-- ****************************************************************
-- *                        Exercícios 1 e 2                      *
-- ****************************************************************


CONNECT EJB01/EJB01

-- DROP TABLE LANCE CASCADE CONSTRAINTS;
-- DROP SEQUENCE SEQ_LANCE;

-- DROP TABLE PRODUTO CASCADE CONSTRAINTS;
-- DROP SEQUENCE SEQ_PRODUTO;

CREATE SEQUENCE SEQ_LANCE;
CREATE SEQUENCE SEQ_PRODUTO;

CREATE TABLE PRODUTO
(ID             NUMBER(5)
   CONSTRAINT PRODUTO_ID_PK
   PRIMARY KEY,
 NOME           VARCHAR2(30) 
   CONSTRAINT PRODUTO_NOME_NN
   NOT NULL,
 DESCRICAO      VARCHAR2(40),
 LANCE_MINIMO  NUMBER(8,2)
   CONSTRAINT PRODUTO_LANCE_MINIMO_NN
   NOT NULL,
 DATA_CADASTRO  DATE
   CONSTRAINT PRODUTO_DATA_CADASTRO_NN
   NOT NULL,
 DATA_VENDA     DATE);

CREATE TABLE LANCE
(ID             NUMBER(5)
   CONSTRAINT LANCE_ID_PK
   PRIMARY KEY,
 VALOR          NUMBER(8,2)
   CONSTRAINT LANCE_VALOR_NN
   NOT NULL,
 DATA_CRIACAO   DATE
   CONSTRAINT LANCE_DATA_CRIACAO_NN
   NOT NULL,
 PRODUTO_ID     NUMBER(5)
   CONSTRAINT LANCE_PRODUTO_FK
   REFERENCES PRODUTO(ID)
   CONSTRAINT LANCE_PRODUTO_ID_NN
   NOT NULL);

INSERT INTO PRODUTO(ID, NOME, DESCRICAO, LANCE_MINIMO, DATA_CADASTRO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV SAMSUNG 20 POL', 'TV SAMSUNG 20 POL TELA PLANA', 2000, SYSDATE);

INSERT INTO LANCE(ID, VALOR, DATA_CRIACAO, PRODUTO_ID)
VALUES(SEQ_LANCE.NEXTVAL, 2100, SYSDATE, SEQ_PRODUTO.CURRVAL);

INSERT INTO LANCE(ID, VALOR, DATA_CRIACAO, PRODUTO_ID)
VALUES(SEQ_LANCE.NEXTVAL, 2200, SYSDATE, SEQ_PRODUTO.CURRVAL);

INSERT INTO PRODUTO(ID, NOME, DESCRICAO, LANCE_MINIMO, DATA_CADASTRO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV SAMSUNG 22 POL', 'TV SAMSUNG 22 POL TELA PLANA', 2500, SYSDATE);

INSERT INTO LANCE(ID, VALOR, DATA_CRIACAO, PRODUTO_ID)
VALUES(SEQ_LANCE.NEXTVAL, 2600, SYSDATE, SEQ_PRODUTO.CURRVAL);

INSERT INTO LANCE(ID, VALOR, DATA_CRIACAO, PRODUTO_ID)
VALUES(SEQ_LANCE.NEXTVAL, 2700, SYSDATE, SEQ_PRODUTO.CURRVAL);

COMMIT;

-- ****************************************************************
-- *                          Exercício 3                         *
-- ****************************************************************

CONNECT EJB02/EJB02

-- DROP TABLE CLIENTE CASCADE CONSTRAINTS;
-- DROP TABLE PEDIDO CASCADE CONSTRAINTS;
-- DROP TABLE ITEM_PEDIDO CASCADE CONSTRAINTS;
-- DROP TABLE PRODUTO CASCADE CONSTRAINTS;

-- DROP SEQUENCE SEQ_CLIENTE;
-- DROP SEQUENCE SEQ_PEDIDO;
-- DROP SEQUENCE SEQ_ITEM_PEDIDO;
-- DROP SEQUENCE SEQ_PRODUTO;

CREATE SEQUENCE SEQ_CLIENTE;
CREATE SEQUENCE SEQ_PEDIDO;
CREATE SEQUENCE SEQ_ITEM_PEDIDO;
CREATE SEQUENCE SEQ_PRODUTO;

CREATE TABLE CLIENTE
(ID             NUMBER(5)
   CONSTRAINT CLIENTE_ID_PK
   PRIMARY KEY,
 NOME           VARCHAR2(30));

CREATE TABLE PRODUTO
(ID             NUMBER(5)
   CONSTRAINT PRODUTO_ID_PK
   PRIMARY KEY,
 NOME           VARCHAR2(30),
 PRECO          NUMBER(9,2));

CREATE TABLE PEDIDO
(ID             NUMBER(5)
   CONSTRAINT PEDIDO_ID_PK
   PRIMARY KEY,
 DATA_EMISSAO   DATE,
 CLIENTE_ID     NUMBER(5)
   CONSTRAINT PEDIDO_CLIENTE_FK
   REFERENCES CLIENTE(ID)
   NOT NULL);

CREATE TABLE ITEM_PEDIDO
(ID             NUMBER(5)
   CONSTRAINT ITEM_PEDIDO_ID_PK
   PRIMARY KEY,
 QTD            NUMBER(5),
 PRODUTO_ID     NUMBER(5)
   CONSTRAINT ITEM_PEDIDO_PRODUTO_FK
   REFERENCES PRODUTO(ID)
   NOT NULL,
 PEDIDO_ID     NUMBER(5)
   CONSTRAINT ITEM_PEDIDO_PEDIDO_FK
   REFERENCES PEDIDO(ID)
   NOT NULL);

INSERT INTO CLIENTE(ID, NOME)
VALUES(SEQ_CLIENTE.NEXTVAL, 'JORGE ALBERTO');

INSERT INTO CLIENTE(ID, NOME)
VALUES(SEQ_CLIENTE.NEXTVAL, 'MARCELO JORGE');

INSERT INTO CLIENTE(ID, NOME)
VALUES(SEQ_CLIENTE.NEXTVAL, 'VINICIUS ALBUQUERQUE');

INSERT INTO PRODUTO(ID, NOME, PRECO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV SAMSUNG 20 POL', 1000);

INSERT INTO PRODUTO(ID, NOME, PRECO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV SAMSUNG 24 POL', 2000);

INSERT INTO PRODUTO(ID, NOME, PRECO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV SAMSUNG 30 POL', 3000);

INSERT INTO PEDIDO(ID, DATA_EMISSAO, CLIENTE_ID)
VALUES(SEQ_PEDIDO.NEXTVAL, SYSDATE, 1);

INSERT INTO PEDIDO(ID, DATA_EMISSAO, CLIENTE_ID)
VALUES(SEQ_PEDIDO.NEXTVAL, SYSDATE, 2);

INSERT INTO PEDIDO(ID, DATA_EMISSAO, CLIENTE_ID)
VALUES(SEQ_PEDIDO.NEXTVAL, SYSDATE, 3);

INSERT INTO ITEM_PEDIDO(ID, QTD, PRODUTO_ID, PEDIDO_ID)
VALUES(SEQ_ITEM_PEDIDO.NEXTVAL, 10, 1, 1);

INSERT INTO ITEM_PEDIDO(ID, QTD, PRODUTO_ID, PEDIDO_ID)
VALUES(SEQ_ITEM_PEDIDO.NEXTVAL, 10, 2, 1);

COMMIT;

-- ****************************************************************
-- *                          Exercício 4                         *
-- ****************************************************************

CONNECT EJB03/EJB03

-- DROP TABLE CLIENTE CASCADE CONSTRAINTS;
-- DROP TABLE PEDIDO CASCADE CONSTRAINTS;
-- DROP TABLE ITEM_PEDIDO CASCADE CONSTRAINTS;
-- DROP TABLE PRODUTO CASCADE CONSTRAINTS;
-- DROP TABLE PAGAMENTO CASCADE CONSTRAINTS;

-- DROP SEQUENCE SEQ_CLIENTE;
-- DROP SEQUENCE SEQ_PEDIDO;
-- DROP SEQUENCE SEQ_ITEM_PEDIDO;
-- DROP SEQUENCE SEQ_PRODUTO;
-- DROP SEQUENCE SEQ_PAGAMENTO;

CREATE SEQUENCE SEQ_CLIENTE;
CREATE SEQUENCE SEQ_PEDIDO;
CREATE SEQUENCE SEQ_ITEM_PEDIDO;
CREATE SEQUENCE SEQ_PRODUTO;
CREATE SEQUENCE SEQ_PAGAMENTO;

CREATE TABLE CLIENTE
(ID             NUMBER(5)
   CONSTRAINT CLIENTE_ID_PK
   PRIMARY KEY,
 NOME           VARCHAR2(30));

CREATE TABLE PRODUTO
(ID             NUMBER(5)
   CONSTRAINT PRODUTO_ID_PK
   PRIMARY KEY,
 NOME           VARCHAR2(30),
 PRECO          NUMBER(9,2));

CREATE TABLE PAGAMENTO
(ID             NUMBER(5)
   CONSTRAINT PAGAMENTO_ID_PK
   PRIMARY KEY,
 DATA_PAGAMENTO DATE,
 NUM_CARTAO     VARCHAR2(16),
 VALOR          NUMBER(9,2));

CREATE TABLE PEDIDO
(ID             NUMBER(5)
   CONSTRAINT PEDIDO_ID_PK
   PRIMARY KEY,
 DATA_EMISSAO   DATE,
 CLIENTE_ID     NUMBER(5)
   CONSTRAINT PEDIDO_CLIENTE_FK
   REFERENCES CLIENTE(ID)
   NOT NULL,
 PAGAMENTO_ID   NUMBER(5)
   CONSTRAINT PEDIDO_PAGAMENTO_FK
   REFERENCES PAGAMENTO(ID)
   NOT NULL);

CREATE TABLE ITEM_PEDIDO
(ID             NUMBER(5)
   CONSTRAINT ITEM_PEDIDO_ID_PK
   PRIMARY KEY,
 QTD            NUMBER(5),
 PRODUTO_ID     NUMBER(5)
   CONSTRAINT ITEM_PEDIDO_PRODUTO_FK
   REFERENCES PRODUTO(ID)
   NOT NULL,
 PEDIDO_ID     NUMBER(5)
   CONSTRAINT ITEM_PEDIDO_PEDIDO_FK
   REFERENCES PEDIDO(ID)
   NOT NULL);

INSERT INTO CLIENTE(ID, NOME)
VALUES(SEQ_CLIENTE.NEXTVAL, 'JORGE ALBERTO');

INSERT INTO CLIENTE(ID, NOME)
VALUES(SEQ_CLIENTE.NEXTVAL, 'MARCELO JORGE');

INSERT INTO CLIENTE(ID, NOME)
VALUES(SEQ_CLIENTE.NEXTVAL, 'VINICIUS ALBUQUERQUE');

INSERT INTO PRODUTO(ID, NOME, PRECO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV SAMSUNG 20 POL', 1000);

INSERT INTO PRODUTO(ID, NOME, PRECO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV SAMSUNG 24 POL', 2000);

INSERT INTO PRODUTO(ID, NOME, PRECO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV SAMSUNG 30 POL', 3000);

INSERT INTO PAGAMENTO(ID, DATA_PAGAMENTO, NUM_CARTAO, VALOR)
VALUES(SEQ_PAGAMENTO.NEXTVAL, SYSDATE, '1111222233334444', 1000);

INSERT INTO PAGAMENTO(ID, DATA_PAGAMENTO, NUM_CARTAO, VALOR)
VALUES(SEQ_PAGAMENTO.NEXTVAL, SYSDATE, '1111222233334444', 2000);

INSERT INTO PAGAMENTO(ID, DATA_PAGAMENTO, NUM_CARTAO, VALOR)
VALUES(SEQ_PAGAMENTO.NEXTVAL, SYSDATE, '5555666677778888', 1000);

INSERT INTO PEDIDO(ID, DATA_EMISSAO, CLIENTE_ID, PAGAMENTO_ID)
VALUES(SEQ_PEDIDO.NEXTVAL, SYSDATE, 1, 1);

INSERT INTO PEDIDO(ID, DATA_EMISSAO, CLIENTE_ID, PAGAMENTO_ID)
VALUES(SEQ_PEDIDO.NEXTVAL, SYSDATE, 2, 2);

INSERT INTO PEDIDO(ID, DATA_EMISSAO, CLIENTE_ID, PAGAMENTO_ID)
VALUES(SEQ_PEDIDO.NEXTVAL, SYSDATE, 3, 3);

INSERT INTO ITEM_PEDIDO(ID, QTD, PRODUTO_ID, PEDIDO_ID)
VALUES(SEQ_ITEM_PEDIDO.NEXTVAL, 10, 1, 1);

INSERT INTO ITEM_PEDIDO(ID, QTD, PRODUTO_ID, PEDIDO_ID)
VALUES(SEQ_ITEM_PEDIDO.NEXTVAL, 10, 2, 1);

COMMIT;

-- ****************************************************************
-- *                       Exercício 6, 7 e 8                     *
-- ****************************************************************

CONNECT EJB01/EJB01

-- drop table conta;
-- drop sequence seq_conta;

create sequence seq_conta;

CREATE TABLE CONTA
(ID		NUMBER(5)
     CONSTRAINT CONTAS_NUMERO_PK PRIMARY KEY,
SALDO		NUMBER(9,2));

INSERT INTO CONTA
VALUES (seq_conta.nextval, 50000);

INSERT INTO CONTA
VALUES (seq_conta.nextval, 150000);

INSERT INTO CONTA
VALUES (seq_conta.nextval, 250000);

INSERT INTO CONTA
VALUES (seq_conta.nextval, 350000);

INSERT INTO CONTA
VALUES (seq_conta.nextval, 450000);

COMMIT;

