DROP USER JPA31 CASCADE;

CREATE USER JPA31 IDENTIFIED BY JPA31;
GRANT CONNECT, RESOURCE TO JPA31;

CONNECT JPA31/JPA31

CREATE SEQUENCE SEQ_CLIENTE;
CREATE SEQUENCE SEQ_CONTA;
CREATE SEQUENCE SEQ_CARTAO;

CREATE TABLE CLIENTE
(ID               NUMBER(5)
   CONSTRAINT CLIENTE_PK
   PRIMARY KEY,
 NOME             VARCHAR2(50)
);

CREATE TABLE CONTA
(ID               NUMBER(5)
    CONSTRAINT CONTA_PK
    PRIMARY KEY,
 DATA_ABERTURA    DATE);

CREATE TABLE CLIENTE_CONTA
(ID_CLIENTE       NUMBER(5)
    CONSTRAINT CLIENTE_CONTA_CLIENTE_FK
    REFERENCES CLIENTE(ID),
 ID_CONTA         NUMBER(5)
    CONSTRAINT CLIENTE_CONTA_CONTA_FK
    REFERENCES CONTA(ID),
CONSTRAINT CLIENTE_CONTA_PK
PRIMARY KEY(ID_CLIENTE, ID_CONTA));

CREATE TABLE CARTAO
(ID               NUMBER(5)
    CONSTRAINT CARTAO_PK
    PRIMARY KEY,
 DATA_EMISSAO     DATE,
 ID_CLIENTE       NUMBER(5),
 ID_CONTA         NUMBER(5),
CONSTRAINT CARTAO_CLIENTE_CONTA_FK
FOREIGN KEY(ID_CLIENTE, ID_CONTA)
REFERENCES CLIENTE_CONTA(ID_CLIENTE, ID_CONTA));
