DROP USER JPA22 CASCADE;
CREATE USER JPA22 IDENTIFIED BY JPA22;
GRANT CONNECT, RESOURCE TO JPA22;

CONNECT JPA22/JPA22

CREATE SEQUENCE SEQ_CLIENTE;

CREATE TABLE CLIENTE
(NUMERO           NUMBER(5)
   CONSTRAINT CLIENTES_NUMERO_PK
   PRIMARY KEY,
 NOME             VARCHAR2(50),
 SALARIO          NUMBER(9,2),
 RUA_RES          VARCHAR2(10),
 NUMERO_RES       VARCHAR2(10),
 COMPLEMENTO_RES  VARCHAR2(10),
 RUA_COM          VARCHAR2(10),
 NUMERO_COM       VARCHAR2(10),
 COMPLEMENTO_COM  VARCHAR2(10)
);

INSERT INTO CLIENTE(NUMERO, NOME, SALARIO)
VALUES (SEQ_CLIENTE.NEXTVAL, 'JULIO CESAR', 2500.00);

INSERT INTO CLIENTE(NUMERO, NOME, SALARIO)
VALUES (SEQ_CLIENTE.NEXTVAL, 'JULIANA SILVA', 1800.00);

INSERT INTO CLIENTE(NUMERO, NOME, SALARIO)
VALUES (SEQ_CLIENTE.NEXTVAL, 'SERGIO ARANTES', 3800.00);

COMMIT;

