DROP USER EJB01 CASCADE;
CREATE USER EJB01 IDENTIFIED BY EJB01;
GRANT CONNECT, RESOURCE TO EJB01;

CONNECT EJB01/EJB01

DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP TABLE PEDIDO CASCADE CONSTRAINTS;
DROP TABLE ITEM_PEDIDO CASCADE CONSTRAINTS;
DROP TABLE PRODUTO CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_CLIENTE;
DROP SEQUENCE SEQ_PEDIDO;
DROP SEQUENCE SEQ_ITEM_PEDIDO;
DROP SEQUENCE SEQ_PRODUTO;

CREATE SEQUENCE SEQ_CLIENTE;
CREATE SEQUENCE SEQ_PEDIDO;
CREATE SEQUENCE SEQ_ITEM_PEDIDO;
CREATE SEQUENCE SEQ_PRODUTO;

CREATE TABLE CLIENTE
(ID             NUMBER(5)
   CONSTRAINT CLIENTE_ID_PK
   PRIMARY KEY,
 NOME           VARCHAR2(30));

CREATE TABLE PRODUTO
(ID             NUMBER(5)
   CONSTRAINT PRODUTO_ID_PK
   PRIMARY KEY,
 NOME           VARCHAR2(30),
 PRECO          NUMBER(9,2));

CREATE TABLE PEDIDO
(ID             NUMBER(5)
   CONSTRAINT PEDIDO_ID_PK
   PRIMARY KEY,
 DATA_EMISSAO   DATE,
 CLIENTE_ID     NUMBER(5)
   CONSTRAINT PEDIDO_CLIENTE_FK
   REFERENCES CLIENTE(ID)
   NOT NULL);

CREATE TABLE ITEM_PEDIDO
(ID             NUMBER(5)
   CONSTRAINT ITEM_PEDIDO_ID_PK
   PRIMARY KEY,
 QTD            NUMBER(5),
 PRODUTO_ID     NUMBER(5)
   CONSTRAINT ITEM_PEDIDO_PRODUTO_FK
   REFERENCES PRODUTO(ID)
   NOT NULL,
 PEDIDO_ID     NUMBER(5)
   CONSTRAINT ITEM_PEDIDO_PEDIDO_FK
   REFERENCES PEDIDO(ID)
   NOT NULL);

INSERT INTO CLIENTE(ID, NOME)
VALUES(SEQ_CLIENTE.NEXTVAL, 'JORGE ALBERTO');

INSERT INTO CLIENTE(ID, NOME)
VALUES(SEQ_CLIENTE.NEXTVAL, 'MARCELO JORGE');

INSERT INTO CLIENTE(ID, NOME)
VALUES(SEQ_CLIENTE.NEXTVAL, 'VINICIUS ALBUQUERQUE');

INSERT INTO PRODUTO(ID, NOME, PRECO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV SAMSUNG 20 POL', 1000);

INSERT INTO PRODUTO(ID, NOME, PRECO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV SAMSUNG 24 POL', 2000);

INSERT INTO PRODUTO(ID, NOME, PRECO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV SAMSUNG 30 POL', 3000);

INSERT INTO PEDIDO(ID, DATA_EMISSAO, CLIENTE_ID)
VALUES(SEQ_PEDIDO.NEXTVAL, SYSDATE, 1);

INSERT INTO PEDIDO(ID, DATA_EMISSAO, CLIENTE_ID)
VALUES(SEQ_PEDIDO.NEXTVAL, SYSDATE, 2);

INSERT INTO PEDIDO(ID, DATA_EMISSAO, CLIENTE_ID)
VALUES(SEQ_PEDIDO.NEXTVAL, SYSDATE, 3);

INSERT INTO ITEM_PEDIDO(ID, QTD, PRODUTO_ID, PEDIDO_ID)
VALUES(SEQ_ITEM_PEDIDO.NEXTVAL, 10, 1, 1);

INSERT INTO ITEM_PEDIDO(ID, QTD, PRODUTO_ID, PEDIDO_ID)
VALUES(SEQ_ITEM_PEDIDO.NEXTVAL, 10, 2, 1);

COMMIT;
