DROP USER JPA28 CASCADE;
CREATE USER JPA28 IDENTIFIED BY JPA28;
GRANT CONNECT, RESOURCE TO JPA28;

CONNECT JPA28/JPA28

CREATE SEQUENCE SEQ_CLIENTE;

CREATE TABLE CLIENTE
(ID           NUMBER(5)
   CONSTRAINT CLIENTES_ID_PK
   PRIMARY KEY,
 NOME         VARCHAR2(50),
 SALARIO      NUMBER(9,2));

CREATE TABLE CLIENTE_TELEFONE
(ID               NUMBER(5),
 TELEFONE         VARCHAR2(50),
CONSTRAINT CLIENTE_TELEFONE_PK
PRIMARY KEY(ID, TELEFONE)
);


INSERT INTO CLIENTE
VALUES (SEQ_CLIENTE.NEXTVAL, 'JULIO CESAR', 2500.00);

INSERT INTO CLIENTE
VALUES (SEQ_CLIENTE.NEXTVAL, 'JULIANA SILVA', 1800.00);

INSERT INTO CLIENTE
VALUES (SEQ_CLIENTE.NEXTVAL, 'SERGIO ARANTES', 3800.00);

INSERT INTO CLIENTE_TELEFONE
VALUES (1, '22223333');

INSERT INTO CLIENTE_TELEFONE
VALUES (2, '44445555');

INSERT INTO CLIENTE_TELEFONE
VALUES (3, '33336666');

COMMIT;
