DROP USER JPA29 CASCADE;
CREATE USER JPA29 IDENTIFIED BY JPA29;
GRANT CONNECT, RESOURCE TO JPA29;

CONNECT JPA29/JPA29

CREATE SEQUENCE SEQ_CLIENTE;

CREATE TABLE CLIENTE
(ID           NUMBER(5)
   CONSTRAINT CLIENTES_NUMERO_PK
   PRIMARY KEY,
 NOME         VARCHAR2(50),
 SALARIO      NUMBER(9,2));

CREATE TABLE CLIENTE_TELEFONE
(ID               NUMBER(5),
 DDD              VARCHAR2(2),
 NUMERO           VARCHAR2(8),
CONSTRAINT CLIENTE_TELEFONE_PK
PRIMARY KEY(ID, DDD, NUMERO)
);

INSERT INTO CLIENTE
VALUES (SEQ_CLIENTE.NEXTVAL, 'JULIO CESAR', 2500.00);

INSERT INTO CLIENTE
VALUES (SEQ_CLIENTE.NEXTVAL, 'JULIANA SILVA', 1800.00);

INSERT INTO CLIENTE
VALUES (SEQ_CLIENTE.NEXTVAL, 'SERGIO ARANTES', 3800.00);

INSERT INTO CLIENTE_TELEFONE
VALUES (1, '21', '22223333');

INSERT INTO CLIENTE_TELEFONE
VALUES (2, '11', '44445555');

INSERT INTO CLIENTE_TELEFONE
VALUES (3, '21', '33336666');

COMMIT;
